[workspace]
members = ["cargo:forte/cli", "cargo:forte/forte-rs-to-ts"]

[dist]
cargo-dist-version = "0.31.0"
ci = ["github"]
targets = [
    "aarch64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
]
installers = ["shell"]

github-build-setup = "../dist/build-setup.yml"

[dist.github-custom-runners]
aarch64-unknown-linux-gnu = "ubuntu-24.04-arm"
