[package]
name = "fn0-ski"
version = "0.1.2"
edition = "2024"
description = "Minimal Winter CG Compatible Runtime"
license = "AGPL-3.0-only"
repository = "https://github.com/NamseEnt/fn0"

[dependencies]
base64 = { workspace = true }
bytes = { workspace = true }
deno_core = "0.394"
deno_error = "0.7"
deno_web = { package = "fn0-deno-web", version = "0.257.0", path = "../../vendor/deno/ext/web" }
deno_fetch = { package = "fn0-deno-fetch", version = "0.250.0", path = "../../vendor/deno/ext/fetch" }
deno_webidl = "0.241"
encoding_rs = "0.8"
futures = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
http-body-util = { workspace = true }

[build-dependencies]
deno_core = "0.394"
deno_error = "0.7"
deno_web = { package = "fn0-deno-web", version = "0.257.0", path = "../../vendor/deno/ext/web" }
deno_fetch = { package = "fn0-deno-fetch", version = "0.250.0", path = "../../vendor/deno/ext/fetch" }
deno_webidl = "0.241"
