[package]
name = "forte-sdk"
version = "0.3.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Runtime library for Forte wasm components (wasi:http p3)"

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
bytes = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
cookie = { workspace = true, features = ["percent-encode"] }
form_urlencoded = { workspace = true }
forte-json = { workspace = true }
forte-macros = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
time = { workspace = true }
uuid = { workspace = true, features = ["v7"] }
wit-bindgen = { workspace = true }
