// Auto-generated by forte build

export const paths = {
  "/signout": () => "/signout",
  "/api/auth/callback/github": () => "/api/auth/callback/github",
  "/": () => "/",
  "/post/:id": ({id}: {id: string}) => `/post/${id}`,
  "/write": () => "/write",
} as const;
