[package]
name = "fn0-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
color-eyre = "0.6.5"
inquire = "0.9.1"
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
fn0 = { path = "../fn0" }
fn0-adapt-cache = "0.1.2"
anyhow = "1"
bytes = "1"
http-body-util = "0.1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
dirs = "6"
fn0-deploy = { version = "=0.1.2", path = "../fn0-deploy" }
hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true, features = ["full"] }
tower = { workspace = true, features = ["util"] }
