[package]
name = "fn0-wasmtime"
version = "0.1.0"
edition = "2024"
description = "Wasmtime wrapper for fn0"
license = "AGPL-3.0-only"
repository = "https://github.com/NamseEnt/fn0"

[dependencies]
wasmtime = { version = "42", default-features = false, features = [
    "runtime",
    "cranelift",
    "component-model",
    "component-model-async",
    "memory-protection-keys",
    "parallel-compilation",
    "cache",
] }
sysinfo = "0.37.2"
anyhow = "1"
zstd = "0.13"
