// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface CloudflareDnsProviderArgsArgs {
    apiToken: pulumi.Input<string>;
    asteriskDomain: pulumi.Input<string>;
    zoneId: pulumi.Input<string>;
}

export interface CwasmBucketArgsArgs {
    accessKeyId: pulumi.Input<string>;
    endpoint: pulumi.Input<string>;
    name: pulumi.Input<string>;
    region: pulumi.Input<string>;
    secretAccessKey: pulumi.Input<string>;
}

export interface DnsProviderArgArgs {
    cloudflare?: pulumi.Input<inputs.CloudflareDnsProviderArgsArgs>;
}

export interface ForteDbArgsArgs {
    apiToken: pulumi.Input<string>;
    groupName: pulumi.Input<string>;
    organizationSlug: pulumi.Input<string>;
}

export interface ForteR2ArgsArgs {
    accessKeyId: pulumi.Input<string>;
    bucket: pulumi.Input<string>;
    endpoint: pulumi.Input<string>;
    publicBaseUrl: pulumi.Input<string>;
    secretAccessKey: pulumi.Input<string>;
}

export interface HostProviderArgArgs {
    ociComputeVm?: pulumi.Input<inputs.OciComputeVmHostProviderArgsArgs>;
}

export interface OciComputeVmHostProviderArgsArgs {
    availabilityDomain: pulumi.Input<string>;
    compartmentId: pulumi.Input<string>;
    envs: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    fingerprint: pulumi.Input<string>;
    imageId: pulumi.Input<string>;
    memoryInGbs: pulumi.Input<number>;
    ocpus: pulumi.Input<number>;
    physicsCpuCores: pulumi.Input<number>;
    privateKeyBase64: pulumi.Input<string>;
    region: pulumi.Input<string>;
    shape: pulumi.Input<string>;
    sshAuthorizedKeys: pulumi.Input<string>;
    sshPrivateKeyBase64: pulumi.Input<string>;
    subnetId: pulumi.Input<string>;
    tenancyId: pulumi.Input<string>;
    userId: pulumi.Input<string>;
}

export interface SiteArgsArgs {
    hostProvider: pulumi.Input<inputs.HostProviderArgArgs>;
    name: pulumi.Input<string>;
}

