// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface OciCwasmBucketInfo {
    accessKeyId: string;
    bucketName: string;
    endpoint: string;
    namespace: string;
    region: string;
    secretAccessKey: string;
}

export interface OciWorkerInfraEnvs {
    OCI_AVAILABILITY_DOMAIN: string;
    OCI_COMPARTMENT_ID: string;
    OCI_FINGERPRINT: string;
    OCI_INSTANCE_CONFIGURATION_ID: string;
    OCI_PRIVATE_KEY_BASE64: string;
    OCI_REGION: string;
    OCI_TENANCY_ID: string;
    OCI_USER_ID: string;
}

export interface WorkerImageRegistry {
    password: string;
    repository: string;
    url: string;
    username: string;
}

