use crate::deps::DependencyPrebundler;
use crate::server::{self, vite_dev, HmrModuleUpdate, ServerConfig, ServerHandle};
use crate::ssr::SsrBundler;
use anyhow::{Context, Result};
use notify_debouncer_mini::{new_debouncer, notify::RecursiveMode};
use std::collections::HashMap;
use std::fs;
use std::net::{SocketAddr, TcpListener};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::mpsc::channel;
use std::time::{Duration, SystemTime};

#[derive(Debug)]
pub struct DevOptions {
    pub project_dir: PathBuf,
    pub port: Option<u16>,
}

impl Default for DevOptions {
    fn default() -> Self {
        Self {
            project_dir: PathBuf::from("."),
            port: None,
        }
    }
}

fn is_port_available(port: u16) -> bool {
    let addr = SocketAddr::from(([0, 0, 0, 0], port));
    TcpListener::bind(addr).is_ok()
}

fn find_available_port(start: u16) -> Option<u16> {
    (start..=65535).find(|&port| is_port_available(port))
}

fn run_codegen(project_dir: &Path) -> Result<()> {
    let rs_dir = project_dir.join("rs");

    let forte_rs_to_ts_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("Failed to get parent of CARGO_MANIFEST_DIR")
        .join("forte-rs-to-ts");

    let status = Command::new("cargo")
        .arg("run")
        .arg("--release")
        .arg("--quiet")
        .arg("--")
        .arg(&rs_dir)
        .current_dir(&forte_rs_to_ts_dir)
        .env_remove("RUSTUP_TOOLCHAIN")
        .stdout(Stdio::null())
        .status()
        .context("Failed to run forte-rs-to-ts. Is it installed?")?;

    if !status.success() {
        anyhow::bail!("forte-rs-to-ts failed with status: {}", status);
    }

    generate_frontend_routes(project_dir)?;

    Ok(())
}

#[derive(Debug)]
struct RouteInfo {
    path: String,
    fe_page_path: String,
}

fn generate_frontend_routes(project_dir: &Path) -> Result<()> {
    let pages_dir = project_dir.join("rs/src/pages");
    let fe_src_dir = project_dir.join("fe/src");

    if !pages_dir.exists() {
        return Ok(());
    }

    let mut routes = Vec::new();
    scan_pages_dir(&pages_dir, &pages_dir, &mut routes)?;

    routes.sort_by(|a, b| {
        let a_dynamic = a.path.contains(':');
        let b_dynamic = b.path.contains(':');
        if a_dynamic != b_dynamic {
            return a_dynamic.cmp(&b_dynamic);
        }
        a.path.cmp(&b.path)
    });

    let mut output = String::new();
    output.push_str("// Auto-generated by forte dev\n\n");
    output.push_str("export const routes: Array<{ path: string; component: () => Promise<{ default: (props: any) => any }>; schema: () => Promise<{ PropsSchema: any }> }> = [\n");

    for route in &routes {
        let fe_props_path = route
            .fe_page_path
            .strip_suffix("/page")
            .map(|s| format!("{}/.props", s))
            .unwrap_or_else(|| route.fe_page_path.clone());
        output.push_str(&format!(
            "  {{ path: \"{}\", component: () => import(\"{}\"), schema: () => import(\"{}\") }},\n",
            route.path, route.fe_page_path, fe_props_path
        ));
    }

    output.push_str("];\n");

    fs::write(fe_src_dir.join("routes.generated.ts"), output)?;

    Ok(())
}

fn scan_pages_dir(base_dir: &Path, current_dir: &Path, routes: &mut Vec<RouteInfo>) -> Result<()> {
    for entry in fs::read_dir(current_dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.is_dir() {
            scan_pages_dir(base_dir, &path, routes)?;
        } else if path.extension().is_some_and(|ext| ext == "rs")
            && has_handler_function(&path)?
            && let Some(route) = path_to_route(base_dir, &path)
        {
            routes.push(route);
        }
    }
    Ok(())
}

fn has_handler_function(path: &Path) -> Result<bool> {
    let content = fs::read_to_string(path)?;
    if content.contains("type Props = Redirect") {
        return Ok(false);
    }
    Ok(content.contains("pub async fn handler"))
}

fn path_to_route(base_dir: &Path, file_path: &Path) -> Option<RouteInfo> {
    let relative = file_path.strip_prefix(base_dir).ok()?;
    let relative_str = relative.to_string_lossy();

    let mut route_path = relative_str
        .trim_end_matches(".rs")
        .trim_end_matches("/mod")
        .replace('\\', "/");

    if route_path == "index" || route_path.is_empty() {
        route_path = "/".to_string();
    } else {
        route_path = route_path
            .replace("/index", "")
            .replace("[", ":")
            .replace("]", "");
        if !route_path.starts_with('/') {
            route_path = format!("/{}", route_path);
        }
    }

    if route_path.starts_with("/api/") {
        return None;
    }

    let fe_page_path = build_fe_page_path(&route_path);

    Some(RouteInfo {
        path: route_path,
        fe_page_path,
    })
}

fn build_fe_page_path(route_path: &str) -> String {
    if route_path == "/" {
        "./pages/index/page".to_string()
    } else {
        let path = route_path
            .replace(":", "[")
            .split('/')
            .filter(|s| !s.is_empty())
            .map(|s| {
                if s.starts_with('[') {
                    format!("{}]", s)
                } else {
                    s.to_string()
                }
            })
            .collect::<Vec<_>>()
            .join("/");
        format!("./pages/{}/page", path)
    }
}

fn build_backend(project_dir: &Path) -> Result<()> {
    let status = Command::new("cargo")
        .arg("build")
        .arg("--release")
        .arg("--quiet")
        .arg("--target")
        .arg("wasm32-wasip2")
        .arg("-p")
        .arg("backend")
        .current_dir(project_dir)
        .status()
        .context("Failed to run cargo build")?;

    if !status.success() {
        anyhow::bail!("cargo build failed with status: {}", status);
    }

    Ok(())
}

fn collect_file_mtimes(dir: &Path, extensions: &[&str]) -> HashMap<PathBuf, SystemTime> {
    let mut mtimes = HashMap::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                mtimes.extend(collect_file_mtimes(&path, extensions));
            } else if let Some(ext) = path.extension() {
                if extensions.iter().any(|e| ext == *e) {
                    if let Ok(metadata) = fs::metadata(&path) {
                        if let Ok(mtime) = metadata.modified() {
                            mtimes.insert(path, mtime);
                        }
                    }
                }
            }
        }
    }
    mtimes
}

pub async fn run(options: DevOptions) -> Result<()> {
    let project_dir = options.project_dir.canonicalize()?;

    let port = match options.port {
        Some(p) => {
            if !is_port_available(p) {
                eprintln!("Error: Port {} is already in use", p);
                std::process::exit(1);
            }
            p
        }
        None => {
            let p = find_available_port(3000)
                .ok_or_else(|| anyhow::anyhow!("No available port found starting from 3000"))?;
            if p != 3000 {
                println!("Port 3000 in use, using port {} instead", p);
            }
            p
        }
    };

    let sqld_port = find_available_port(8080)
        .ok_or_else(|| anyhow::anyhow!("No available port found for sqld starting from 8080"))?;
    let mut _sqld = crate::sqld::start(&project_dir, sqld_port).await?;
    println!("sqld running on port {}", sqld_port);

    run_codegen(&project_dir)?;
    build_backend(&project_dir)?;

    let use_vite_dev = true;

    let fe_dir = project_dir.join("fe");
    let mut vite: Option<vite_dev::Vite> = None;

    if use_vite_dev {
        let v = vite_dev::spawn_vite(&fe_dir, port)?;
        vite_dev::wait_for_vite_ready(&v.socket_path).await?;
        vite = Some(v);
    }

    let prebundler = DependencyPrebundler::new(&project_dir);
    let prebundler = std::sync::Arc::new(std::sync::Mutex::new(prebundler));

    let backend_path = project_dir
        .join("target/wasm32-wasip2/release/backend.wasm")
        .to_string_lossy()
        .to_string();

    let frontend_path = String::new();
    let public_dir = project_dir.join("fe/public");

    let env_vars = server::create_env_vars(&project_dir);
    {
        let mut vars = env_vars.write().unwrap();
        if !vars.iter().any(|(k, _)| k == "TURSO_URL") {
            vars.push((
                "TURSO_URL".to_string(),
                format!("http://127.0.0.1:{}", sqld_port),
            ));
        }
    }

    let config = ServerConfig {
        port,
        backend_path,
        frontend_path,
        public_dir,
        project_root: project_dir.clone(),
        dev_mode: true,
        use_vite_dev,
        vite_socket_path: vite.as_ref().map(|v| v.socket_path.clone()),
        prebundler,
        env_vars,
    };

    let handle = server::run(config).await?;

    let result = run_watch_loop(&project_dir, handle).await;

    if let Some(mut v) = vite {
        let _ = v.child.kill();
    }

    _sqld.kill();

    result
}

async fn run_watch_loop(project_dir: &Path, handle: ServerHandle) -> Result<()> {
    let (tx, rx) = channel();

    let mut debouncer = new_debouncer(Duration::from_millis(100), tx)?;

    let rs_dir = project_dir.join("rs/src");
    let fe_src_dir = project_dir.join("fe/src");
    let env_file = project_dir.join(".env");

    debouncer
        .watcher()
        .watch(&rs_dir, RecursiveMode::Recursive)?;
    debouncer
        .watcher()
        .watch(&fe_src_dir, RecursiveMode::Recursive)?;
    if env_file.exists() {
        debouncer
            .watcher()
            .watch(&env_file, RecursiveMode::NonRecursive)?;
    }

    let mut known_rs_mtimes = collect_file_mtimes(&rs_dir, &["rs"]);
    let mut known_fe_mtimes = collect_file_mtimes(&fe_src_dir, &["tsx", "ts", "jsx", "js", "css"]);
    let mut known_env_mtime = fs::metadata(&env_file).ok().and_then(|m| m.modified().ok());

    loop {
        match rx.recv() {
            Ok(Ok(events)) => {
                let rs_changes: Vec<_> = events
                    .iter()
                    .filter(|e| {
                        e.path.starts_with(&rs_dir)
                            && e.path.extension().is_some_and(|ext| ext == "rs")
                            && !e.path.ends_with("route_generated.rs")
                    })
                    .filter(|e| {
                        let current_mtime =
                            fs::metadata(&e.path).ok().and_then(|m| m.modified().ok());
                        match (current_mtime, known_rs_mtimes.get(&e.path)) {
                            (Some(current), Some(known)) => current > *known,
                            (Some(_), None) => true,
                            _ => false,
                        }
                    })
                    .collect();

                let fe_changes: Vec<_> = events
                    .iter()
                    .filter(|e| {
                        e.path.starts_with(&fe_src_dir)
                            && e.path.extension().is_some_and(|ext| {
                                ext == "tsx"
                                    || ext == "ts"
                                    || ext == "jsx"
                                    || ext == "js"
                                    || ext == "css"
                            })
                            && !is_generated_file(&e.path)
                    })
                    .filter(|e| {
                        let current_mtime =
                            fs::metadata(&e.path).ok().and_then(|m| m.modified().ok());
                        match (current_mtime, known_fe_mtimes.get(&e.path)) {
                            (Some(current), Some(known)) => current > *known,
                            (Some(_), None) => true,
                            _ => false,
                        }
                    })
                    .collect();

                let env_changed = events.iter().any(|e| e.path == env_file) && {
                    let current_mtime = fs::metadata(&env_file).ok().and_then(|m| m.modified().ok());
                    match (current_mtime, known_env_mtime) {
                        (Some(current), Some(known)) => current > known,
                        (Some(_), None) => true,
                        _ => false,
                    }
                };

                if env_changed {
                    known_env_mtime = fs::metadata(&env_file).ok().and_then(|m| m.modified().ok());
                    let new_vars = server::load_env_file(project_dir);
                    handle.fn0.update_env(new_vars);
                }

                if !rs_changes.is_empty() {
                    let result = rebuild_backend(project_dir, &handle).await;
                    known_rs_mtimes = collect_file_mtimes(&rs_dir, &["rs"]);

                    while rx.try_recv().is_ok() {}

                    if let Err(e) = result {
                        eprintln!("[watch] Backend rebuild failed: {}", e);
                    } else {
                        handle.hmr.send_reload();
                    }
                }

                if !fe_changes.is_empty() {
                    for e in &fe_changes {
                        handle_frontend_change(&e.path, &handle);
                    }

                    known_fe_mtimes =
                        collect_file_mtimes(&fe_src_dir, &["tsx", "ts", "jsx", "js", "css"]);
                }
            }
            Ok(Err(error)) => {
                eprintln!("[watch] Error: {:?}", error);
            }
            Err(e) => {
                eprintln!("[watch] Channel error: {:?}", e);
                break;
            }
        }
    }

    Ok(())
}

fn handle_frontend_change(file_path: &Path, handle: &ServerHandle) {
    if let Some(ts) = &handle.transform_server {
        ts.invalidate_module(file_path);

        if let Some(update) = ts.get_hmr_update(file_path) {
            if update.needs_full_reload {
                handle.hmr.send_reload();
            } else {
                handle.hmr.send_update(vec![HmrModuleUpdate {
                    id: update.boundary.clone(),
                    accepted_by: update.boundary,
                }]);
            }
        } else {
            handle.hmr.send_reload();
        }
    } else {
        handle.hmr.send_reload();
    }
}

async fn rebuild_backend(project_dir: &Path, handle: &ServerHandle) -> Result<()> {
    run_codegen(project_dir)?;
    build_backend(project_dir)?;
    handle.cache.invalidate("backend").await;
    Ok(())
}

fn is_generated_file(path: &Path) -> bool {
    let path_str = path.to_string_lossy();
    path_str.contains(".generated/")
        || path_str.ends_with(".props.ts")
        || path_str.ends_with("routes.generated.ts")
}
