// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface CloudflareEnvsArgs {
    CLOUDFLARE_API_TOKEN: pulumi.Input<string>;
    CLOUDFLARE_ASTERISK_DOMAIN: pulumi.Input<string>;
    CLOUDFLARE_ZONE_ID: pulumi.Input<string>;
}

export interface OciWorkerInfraEnvsArgs {
    OCI_COMPARTMENT_ID: pulumi.Input<string>;
    OCI_FINGERPRINT: pulumi.Input<string>;
    OCI_INSTANCE_CONFIGURATION_ID: pulumi.Input<string>;
    OCI_PRIVATE_KEY_BASE64: pulumi.Input<string>;
    OCI_REGION: pulumi.Input<string>;
    OCI_TENANCY_ID: pulumi.Input<string>;
    OCI_USER_ID: pulumi.Input<string>;
}
