[package]
name = "measure-cpu-time"
version = "0.1.0"
edition = "2024"
description = "CPU time measurement utilities"
license = "AGPL-3.0-only"
repository = "https://github.com/NamseEnt/fn0"

[dependencies]

[dev-dependencies]
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "time", "sync", "test-util"] }
