// Auto-generated by forte build

export const paths = {
  "/oauth/cli/authorize": () => "/oauth/cli/authorize",
  "/oauth/github/callback": () => "/oauth/github/callback",
  "/projects": () => "/projects",
  "/forte": () => "/forte",
  "/docs/:section/:page": ({section, page}: {section: string; page: string}) => `/docs/${section}/${page}`,
  "/docs/:page": ({page}: {page: string}) => `/docs/${page}`,
  "/docs": () => "/docs",
  "/": () => "/",
  "/tokens": () => "/tokens",
  "/login": () => "/login",
} as const;
