// Auto-generated by forte build

export const routes: Array<{ path: string; component: () => Promise<{ default: (props: any) => any }>; schema: () => Promise<{ PropsSchema: any }> }> = [
  { path: "/", component: () => import("./pages/index/page"), schema: () => import("./pages/index/.props") },
  { path: "/oauth/cli/authorize", component: () => import("./pages/oauth/cli/authorize/page"), schema: () => import("./pages/oauth/cli/authorize/.props") },
  { path: "/tokens", component: () => import("./pages/tokens/page"), schema: () => import("./pages/tokens/.props") },
];
