[package]
name = "fn0-deploy"
version = "0.1.5"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Deploy client for fn0 cloud"

[dependencies]
anyhow = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tar = { workspace = true }
tokio = { workspace = true, features = ["time"] }
urlencoding = "2.1"
