[package]
name = "forte-json"
version = "0.1.0"
edition = "2024"
description = "Streaming JSON serializer for the Forte web framework"
license = "AGPL-3.0-only"
repository = "https://github.com/NamseEnt/fn0"

[dependencies]
serde = { version = "1.0" }
serde_json = "1.0"
bytes = "1.5"
futures = "0.3"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
