[package]
name = "hq"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.release]
release = false

[dependencies]
aes-gcm = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
boxcar = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
color-eyre = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true, features = ["full"] }
libsql = { workspace = true }
oci-rust-sdk = { workspace = true, features = ["core"] }
opendal = { workspace = true }
opentelemetry = { workspace = true, features = ["logs", "metrics"] }
opentelemetry-otlp = { workspace = true, features = [
    "grpc-tonic",
    "reqwest-client",
    "metrics",
    "logs",
] }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }
rand = { workspace = true }
reqsign = { workspace = true }
reqwest = { workspace = true }
russh = { workspace = true }
rustls = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
singleflight = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
mockall = { workspace = true }
wiremock = { workspace = true }

[build-dependencies]
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
