use super::model::*;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

pub(super) fn generate_code(
    pages: &[PageInfo],
    hooks: &[HookInfo],
    actions: &[ActionInfo],
    queue_tasks: &[QueueTaskInfo],
    admin_tasks: &[AdminTaskInfo],
    static_files: &[StaticFileInfo],
    wit_dir: &str,
) -> TokenStream {
    let mut all_module_decls: Vec<(String, TokenStream)> = Vec::new();
    for (name, ts) in generate_module_declarations(pages) {
        all_module_decls.push((name, ts));
    }
    for (name, ts) in generate_hook_module_declarations(hooks) {
        all_module_decls.push((name, ts));
    }
    for (name, ts) in generate_action_module_declarations(actions) {
        all_module_decls.push((name, ts));
    }
    all_module_decls.sort_by(|(a, _), (b, _)| a.cmp(b));
    let module_declarations: Vec<TokenStream> =
        all_module_decls.into_iter().map(|(_, ts)| ts).collect();
    let hook_module_declarations: Vec<TokenStream> = Vec::new();
    let action_module_declarations: Vec<TokenStream> = Vec::new();
    let route_matches = generate_route_matches(pages);
    let redirect_enum = generate_redirect_enum(pages);
    let hook_handler = generate_hook_handler(hooks);
    let action_handler = generate_action_handler(actions);
    let enqueue_module = generate_enqueue_module(queue_tasks);
    let queue_task_execute_handler = generate_queue_task_execute_handler(queue_tasks);
    let admin_task_handler = generate_admin_task_handler(admin_tasks);
    let classify_route_fn = generate_classify_route(pages);

    let static_file_chain = {
        let matches: Vec<TokenStream> = static_files
            .iter()
            .map(|f| {
                let route_path = &f.route_path;
                let content_type = &f.content_type;
                let include_path = &f.include_path;
                quote! {
                    if path == #route_path {
                        return Ok(Response::builder()
                            .status(StatusCode::OK)
                            .header("content-type", #content_type)
                            .body(Body::from(include_bytes!(#include_path).to_vec()))
                            .unwrap());
                    }
                }
            })
            .collect();
        quote! { #(#matches)* }
    };

    let route_chain = if route_matches.is_empty() {
        quote! {
            Ok(Response::builder()
                .status(StatusCode::NOT_FOUND)
                .body(Body::empty())
                .unwrap())
        }
    } else {
        let needs_path_segments = pages
            .iter()
            .any(|p| has_dynamic_segments(&p.route_segments));
        let path_segments_decl = if needs_path_segments {
            quote! {
                let path_segments: Vec<&str> = path.trim_start_matches('/').split('/').collect();
            }
        } else {
            quote! {}
        };
        let first = &route_matches[0];
        let rest = &route_matches[1..];
        quote! {
            #path_segments_decl
            #first
            #(else #rest)*
            else {
                Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::empty())
                    .unwrap())
            }
        }
    };

    let proxy_world_inline = "package forte:user; world service-export { import wasi:http/types@0.3.0-rc-2026-03-15; export wasi:http/handler@0.3.0-rc-2026-03-15; }";

    quote! {
        // Auto-generated by build.rs

        #(#module_declarations)*
        #(#hook_module_declarations)*
        #(#action_module_declarations)*

        use forte_sdk::anyhow::Result;
        use forte_sdk::http::{Request, Response, StatusCode, body::Body, HeaderMap};
        use forte_sdk::http_header::{COOKIE, LOCATION, SET_COOKIE};
        use forte_sdk::*;

        #redirect_enum

        #enqueue_module

        #[allow(clippy::crate_in_macro_def)]
        mod proxy {
            forte_sdk::wit_bindgen::generate!({
                inline: #proxy_world_inline,
                path: #wit_dir,
                world: "service-export",
                default_bindings_module: "crate::route_generated::proxy",
                pub_export_macro: true,
                async: true,
                features: ["clocks-timezone"],
                with: {
                    "wasi:http/handler@0.3.0-rc-2026-03-15": generate,
                    "wasi:http/types@0.3.0-rc-2026-03-15": forte_sdk::bindings::wasi::http::types,
                    "wasi:clocks/types@0.3.0-rc-2026-03-15": forte_sdk::bindings::wasi::clocks::types,
                },
                runtime_path: "forte_sdk::wit_bindgen::rt",
            });
        }

        struct Server;

        impl proxy::exports::wasi::http::handler::Guest for Server {
            async fn handle(
                req: forte_sdk::bindings::wasi::http::types::Request,
            ) -> core::result::Result<
                forte_sdk::bindings::wasi::http::types::Response,
                forte_sdk::bindings::wasi::http::types::ErrorCode,
            > {
                forte_sdk::serve::serve(req, |request| async move {
                    dispatch(request).await
                }).await
            }
        }

        proxy::export!(Server);

        async fn dispatch(request: Request<Vec<u8>>) -> Result<Response<Body>> {
            let path_for_route = request.uri().path().to_string();
            let key = classify_route(&path_for_route);
            let result = dispatch_inner(request).await;
            result.map(|mut resp| {
                if let Ok(v) = forte_sdk::http::HeaderValue::from_str(&key) {
                    resp.headers_mut().insert("x-fn0-execution-time-metric-key", v);
                }
                resp
            })
        }

        #classify_route_fn

        async fn dispatch_inner(request: Request<Vec<u8>>) -> Result<Response<Body>> {
            let (parts, body_bytes) = request.into_parts();
            let headers = parts.headers;
            let path = parts.uri.path().to_string();
            let method = parts.method;
            let mut cookie_jar = make_cookie_jar(&headers);

            let Some(uri_authority) = parts.uri.authority() else {
                return Ok(Response::builder()
                    .status(StatusCode::BAD_REQUEST)
                    .body(Body::from("Missing authority in request URI"))
                    .unwrap());
            };
            let uri_authority = uri_authority.as_str();
            let path = path.as_str();

            if let Some(hook_name) = path.strip_prefix("/__self_invoke/") {
                return handle_hook(hook_name, uri_authority, &method, &headers, &mut cookie_jar, &body_bytes).await;
            }

            if let Some(action_name) = path.strip_prefix("/__forte_action/") {
                return handle_action(action_name, uri_authority, &method, &headers, &mut cookie_jar, &body_bytes).await;
            }

            if path == "/__fn0_queue_task/execute" {
                return handle_queue_task_execute(&body_bytes).await;
            }

            if let Some(task_name) = path.strip_prefix("/__forte_admin/") {
                return handle_admin_task(task_name, &headers, &body_bytes).await;
            }

            #static_file_chain

            #route_chain
        }

        #hook_handler

        #action_handler

        #queue_task_execute_handler

        #admin_task_handler

        fn make_cookie_jar(headers: &HeaderMap) -> cookie::CookieJar {
            let mut jar = cookie::CookieJar::new();
            let Some(cookie) = headers.get(COOKIE) else {
                return jar;
            };
            let Ok(cookie_str) = cookie.to_str() else {
                return jar;
            };

            for cookie in cookie::Cookie::split_parse_encoded(cookie_str) {
                let Ok(cookie) = cookie else { continue };
                jar.add_original(cookie.into_owned());
            }

            jar
        }

        fn build_response_with_cookies(mut response: Response<Body>, cookie_jar: &cookie::CookieJar) -> Response<Body> {
            for cookie in cookie_jar.delta() {
                if let Ok(value) = cookie.encoded().to_string().parse() {
                    response.headers_mut().append(SET_COOKIE, value);
                }
            }
            response
        }
    }
}

fn generate_module_declarations(pages: &[PageInfo]) -> Vec<(String, TokenStream)> {
    pages
        .iter()
        .map(|page| {
            let module_ident = format_ident!("{}", page.module_name);
            let module_path = &page.module_path;

            let allow_attr = if has_dynamic_segments(&page.route_segments) {
                quote! { #[allow(non_snake_case)] }
            } else {
                quote! {}
            };

            (
                page.module_name.clone(),
                quote! {
                    #allow_attr
                    #[path = #module_path]
                    mod #module_ident;
                },
            )
        })
        .collect()
}

fn has_dynamic_segments(segments: &[RouteSegment]) -> bool {
    segments
        .iter()
        .any(|s| matches!(s, RouteSegment::Dynamic(_)))
}

fn generate_hook_module_declarations(hooks: &[HookInfo]) -> Vec<(String, TokenStream)> {
    hooks
        .iter()
        .map(|hook| {
            let module_ident = format_ident!("{}", hook.module_name);
            let module_path = &hook.module_path;

            (
                hook.module_name.clone(),
                quote! {
                    #[path = #module_path]
                    mod #module_ident;
                },
            )
        })
        .collect()
}

fn generate_route_matches(pages: &[PageInfo]) -> Vec<TokenStream> {
    pages
        .iter()
        .map(|page| {
            let module_name = format_ident!("{}", page.module_name);

            // Generate route condition
            let route_condition = if has_dynamic_segments(&page.route_segments) {
                generate_dynamic_route_condition(&page.route_segments)
            } else {
                let route_path = &page.route_path;
                quote! { path == #route_path }
            };


            // Generate path params extraction (if dynamic)
            let path_params_extraction = if let Some(path_params) = &page.path_params {
                generate_path_params_extraction(&module_name, &page.route_segments, path_params)
            } else {
                quote! {}
            };

            let search_params_extraction = if let Some(fields) = &page.search_params {
                let field_parsers = generate_search_field_parsers(fields);
                let field_names: Vec<_> =
                    fields.iter().map(|f| format_ident!("{}", f.name)).collect();
                quote! {
                    use std::collections::HashMap;
                    let query = parts.uri.query().unwrap_or("");
                    let query_params: HashMap<String, String> = forte_sdk::form_urlencoded::parse(query.as_bytes())
                        .map(|(k, v)| (k.into_owned(), v.into_owned()))
                        .collect();
                    #(#field_parsers)*
                    let search_params = #module_name::SearchParams {
                        #(#field_names),*
                    };
                }
            } else {
                quote! {}
            };

            // Generate handler call based on what params exist
            let handler_call = match (&page.path_params, &page.search_params) {
                (Some(_), Some(_)) => quote! {
                    #module_name::handler(req, path_params, search_params).await
                },
                (Some(_), None) => quote! {
                    #module_name::handler(req, path_params).await
                },
                (None, Some(_)) => quote! {
                    #module_name::handler(req, search_params).await
                },
                (None, None) => quote! {
                    #module_name::handler(req).await
                },
            };

            // Different response handling for redirect-only pages vs props pages
            let response_handling = if page.is_redirect_only {
                quote! {
                    match #handler_call {
                        Ok(redirect) => {
                            Ok(build_response_with_cookies(
                                Response::builder()
                                    .status(StatusCode::FOUND)
                                    .header(LOCATION, redirect.to_path())
                                    .body(Body::empty())
                                    .unwrap(),
                                &cookie_jar,
                            ))
                        }
                        Err(e) => {
                            eprintln!("Error at {}: {:?}", path, e);
                            Ok(Response::builder()
                                .status(StatusCode::INTERNAL_SERVER_ERROR)
                                .body(Body::from("Internal Server Error"))
                                .unwrap())
                        }
                    }
                }
            } else {
                let ok_response = if page.is_api {
                    quote! {
                        Response::builder()
                            .status(StatusCode::OK)
                            .header("content-type", "application/json")
                            .body(Body::from(body_bytes))
                            .unwrap()
                    }
                } else {
                    quote! {
                        Response::builder()
                            .status(StatusCode::OK)
                            .header("x-fn0-next", "js")
                            .body(Body::from(body_bytes))
                            .unwrap()
                    }
                };
                quote! {
                    match #handler_call {
                        Ok(props) => {
                            let body_bytes = forte_json::to_vec(&props);
                            Ok(build_response_with_cookies(#ok_response, &cookie_jar))
                        }
                        Err(e) => {
                            if let Some(redirect) = e.downcast_ref::<Redirect>() {
                                Ok(build_response_with_cookies(
                                    Response::builder()
                                        .status(StatusCode::FOUND)
                                        .header(LOCATION, redirect.to_path())
                                        .body(Body::empty())
                                        .unwrap(),
                                    &cookie_jar,
                                ))
                            } else {
                                eprintln!("Error at {}: {:?}", path, e);
                                Ok(Response::builder()
                                    .status(StatusCode::INTERNAL_SERVER_ERROR)
                                    .body(Body::from("Internal Server Error"))
                                    .unwrap())
                            }
                        }
                    }
                }
            };

            quote! {
                if #route_condition {
                    #path_params_extraction
                    #search_params_extraction

                    let req = ForteRequest {
                        uri_authority,
                        method: &method,
                        headers: &headers,
                        jar: &mut cookie_jar,
                        raw_body: &body_bytes,
                        body: (),
                    };

                    #response_handling
                }
            }
        })
        .collect()
}

fn generate_dynamic_route_condition(segments: &[RouteSegment]) -> TokenStream {
    let segment_count = segments.len();
    let segment_checks: Vec<TokenStream> = segments
        .iter()
        .enumerate()
        .filter_map(|(i, seg)| {
            if let RouteSegment::Static(s) = seg {
                if i == 0 {
                    Some(quote! { path_segments.first() == Some(&#s) })
                } else {
                    Some(quote! { path_segments.get(#i) == Some(&#s) })
                }
            } else {
                None // Dynamic segments match anything
            }
        })
        .collect();

    if segment_checks.is_empty() {
        quote! {
            path_segments.len() == #segment_count
        }
    } else {
        quote! {
            path_segments.len() == #segment_count && #(#segment_checks)&&*
        }
    }
}

fn generate_path_params_extraction(
    module_name: &syn::Ident,
    route_segments: &[RouteSegment],
    path_params: &[PathParamField],
) -> TokenStream {
    let extractions: Vec<TokenStream> = route_segments
        .iter()
        .enumerate()
        .filter_map(|(i, seg)| {
            if let RouteSegment::Dynamic(param_name) = seg {
                // Find the corresponding PathParamField
                let field = path_params.iter().find(|f| &f.name == param_name)?;
                let field_ident = format_ident!("{}", field.name);
                let inner_type: TokenStream = field.inner_type.parse().unwrap();

                if field.inner_type == "String" {
                    Some(quote! {
                        let #field_ident: String = path_segments[#i].to_string();
                    })
                } else {
                    Some(quote! {
                        let #field_ident: #inner_type = match path_segments[#i].parse::<#inner_type>() {
                            Ok(v) => v,
                            Err(_) => {
                                return Ok(Response::builder()
                                    .status(StatusCode::BAD_REQUEST)
                                    .body(Body::from(format!("Invalid path parameter: {}", stringify!(#field_ident))))
                                    .unwrap());
                            }
                        };
                    })
                }
            } else {
                None
            }
        })
        .collect();

    let field_names: Vec<_> = path_params
        .iter()
        .map(|f| format_ident!("{}", f.name))
        .collect();

    quote! {
        #(#extractions)*
        let path_params = #module_name::PathParams { #(#field_names),* };
    }
}

fn generate_search_field_parsers(fields: &[SearchParamField]) -> Vec<TokenStream> {
    fields
        .iter()
        .map(|field| {
            let field_name = format_ident!("{}", field.name);
            let field_name_str = &field.name;
            let inner_type: TokenStream = field.inner_type.parse().unwrap();

            if field.is_optional {
                if field.inner_type == "String" {
                    quote! {
                        let #field_name: Option<String> = query_params.get(#field_name_str).cloned();
                    }
                } else {
                    quote! {
                        let #field_name: Option<#inner_type> = query_params
                            .get(#field_name_str)
                            .and_then(|v| v.parse::<#inner_type>().ok());
                    }
                }
            } else if field.inner_type == "String" {
                quote! {
                    let Some(#field_name) = query_params.get(#field_name_str).cloned() else {
                        return Ok(Response::builder()
                            .status(StatusCode::BAD_REQUEST)
                            .body(Body::from(format!("Missing required query parameter: {}", #field_name_str)))
                            .unwrap());
                    };
                }
            } else {
                quote! {
                    let #field_name: #inner_type = match query_params.get(#field_name_str) {
                        Some(v) => match v.parse::<#inner_type>() {
                            Ok(parsed) => parsed,
                            Err(_) => {
                                return Ok(Response::builder()
                                    .status(StatusCode::BAD_REQUEST)
                                    .body(Body::from(format!("Invalid value for query parameter: {}", #field_name_str)))
                                    .unwrap());
                            }
                        },
                        None => {
                            return Ok(Response::builder()
                                .status(StatusCode::BAD_REQUEST)
                                .body(Body::from(format!("Missing required query parameter: {}", #field_name_str)))
                                .unwrap());
                        }
                    };
                }
            }
        })
        .collect()
}

fn generate_redirect_enum(pages: &[PageInfo]) -> TokenStream {
    let variants: Vec<TokenStream> = pages
        .iter()
        .map(|page| {
            let variant_name = page_to_variant_name(&page.route_segments);
            let variant_ident = format_ident!("{}", variant_name);

            if let Some(path_params) = &page.path_params {
                let fields: Vec<TokenStream> = path_params
                    .iter()
                    .map(|p| {
                        let name = format_ident!("{}", p.name);
                        let ty: TokenStream = p.inner_type.parse().unwrap();
                        quote! { #name: #ty }
                    })
                    .collect();
                quote! { #variant_ident { #(#fields),* } }
            } else {
                quote! { #variant_ident }
            }
        })
        .collect();

    let to_path_arms: Vec<TokenStream> = pages
        .iter()
        .map(|page| {
            let variant_name = page_to_variant_name(&page.route_segments);
            let variant_ident = format_ident!("{}", variant_name);

            if let Some(path_params) = &page.path_params {
                let field_names: Vec<_> = path_params
                    .iter()
                    .map(|p| format_ident!("{}", p.name))
                    .collect();

                // Build path with dynamic segments
                let path_parts: Vec<TokenStream> = page
                    .route_segments
                    .iter()
                    .map(|seg| match seg {
                        RouteSegment::Static(s) => quote! { #s.to_string() },
                        RouteSegment::Dynamic(name) => {
                            let name_ident = format_ident!("{}", name);
                            quote! { #name_ident.to_string() }
                        }
                    })
                    .collect();

                quote! {
                    Redirect::#variant_ident { #(#field_names),* } => {
                        format!("/{}", [#(#path_parts),*].join("/"))
                    }
                }
            } else {
                let route_path = &page.route_path;
                quote! {
                    Redirect::#variant_ident => #route_path.to_string()
                }
            }
        })
        .collect();

    quote! {
        #[derive(Debug, serde::Serialize, serde::Deserialize)]
        #[allow(non_camel_case_types)]
        pub enum Redirect {
            External { url: String },
            #(#variants),*
        }

        impl Redirect {
            pub fn to_path(&self) -> String {
                match self {
                    Redirect::External { url } => url.clone(),
                    #(#to_path_arms),*
                }
            }
        }

        impl std::fmt::Display for Redirect {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "Redirect to {}", self.to_path())
            }
        }

        impl std::error::Error for Redirect {}
    }
}

fn page_to_variant_name(segments: &[RouteSegment]) -> String {
    // /post -> Post
    // /post/id (static) -> PostId
    // /post/[id] -> Post_id_
    // /post/[id]/comment -> Post_id_Comment
    if segments.is_empty() {
        return "Index".to_string();
    }

    segments
        .iter()
        .map(|seg| match seg {
            RouteSegment::Static(s) => {
                let mut chars = s.chars();
                match chars.next() {
                    None => String::new(),
                    Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                }
            }
            RouteSegment::Dynamic(name) => {
                format!("_{}_", name)
            }
        })
        .collect()
}

fn generate_hook_handler(hooks: &[HookInfo]) -> TokenStream {
    if hooks.is_empty() {
        return quote! {
            async fn handle_hook(
                hook_name: &str,
                _uri_authority: &str,
                _method: &http::Method,
                _headers: &HeaderMap,
                _cookie_jar: &mut cookie::CookieJar,
                _body_bytes: &[u8],
            ) -> Result<Response<Body>> {
                Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::from(format!("Hook '{}' not found", hook_name)))
                    .unwrap())
            }
        };
    }

    let hook_matches: Vec<TokenStream> = hooks
        .iter()
        .map(|hook| {
            let name = &hook.name;
            let module_name = format_ident!("{}", hook.module_name);

            quote! {
                #name => {
                    let input: #module_name::Input = forte_json::from_slice(body_bytes)?;
                    let req = ForteRequest {
                        uri_authority,
                        method,
                        headers,
                        jar: cookie_jar,
                        raw_body: body_bytes,
                        body: input,
                    };
                    let output = #module_name::handler(req).await;
                    let json = forte_json::to_vec(&output);
                    Ok(build_response_with_cookies(
                        Response::builder()
                            .status(StatusCode::OK)
                            .header("content-type", "application/json")
                            .body(Body::from(json))
                            .unwrap(),
                        cookie_jar,
                    ))
                }
            }
        })
        .collect();

    quote! {
        #[forte_sdk::tracing::instrument(
            name = "handle_hook",
            skip_all,
            fields(hook = hook_name),
        )]
        async fn handle_hook(
            hook_name: &str,
            uri_authority: &str,
            method: &http::Method,
            headers: &HeaderMap,
            cookie_jar: &mut cookie::CookieJar,
            body_bytes: &[u8],
        ) -> Result<Response<Body>> {
            match hook_name {
                #(#hook_matches)*
                _ => Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::from(format!("Hook '{}' not found", hook_name)))
                    .unwrap()),
            }
        }
    }
}

fn generate_action_module_declarations(_actions: &[ActionInfo]) -> Vec<(String, TokenStream)> {
    Vec::new()
}

fn generate_action_handler(actions: &[ActionInfo]) -> TokenStream {
    if actions.is_empty() {
        return quote! {
            async fn handle_action(
                action_name: &str,
                _uri_authority: &str,
                _method: &http::Method,
                _headers: &HeaderMap,
                _cookie_jar: &mut cookie::CookieJar,
                _body_bytes: &[u8],
            ) -> Result<Response<Body>> {
                Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::from(format!("Action '{}' not found", action_name)))
                    .unwrap())
            }
        };
    }

    let action_matches: Vec<TokenStream> = actions
        .iter()
        .map(|action| {
            let name = &action.name;
            let module_ident = format_ident!("{}", action.name);

            quote! {
                #name => {
                    let input: crate::actions::#module_ident::Input = match forte_json::from_slice(body_bytes) {
                        Ok(v) => v,
                        Err(e) => {
                            return Ok(Response::builder()
                                .status(StatusCode::BAD_REQUEST)
                                .body(Body::from(format!("invalid request body: {}", e)))
                                .unwrap());
                        }
                    };
                    let req = ForteRequest {
                        uri_authority,
                        method,
                        headers,
                        jar: cookie_jar,
                        raw_body: body_bytes,
                        body: input,
                    };
                    let output = crate::actions::#module_ident::handler(req).await;
                    let json = forte_json::to_vec(&output);
                    Ok(build_response_with_cookies(
                        Response::builder()
                            .status(StatusCode::OK)
                            .header("content-type", "application/json")
                            .body(Body::from(json))
                            .unwrap(),
                        cookie_jar,
                    ))
                }
            }
        })
        .collect();

    quote! {
        #[forte_sdk::tracing::instrument(
            name = "handle_action",
            skip_all,
            fields(action = action_name),
        )]
        async fn handle_action(
            action_name: &str,
            uri_authority: &str,
            method: &http::Method,
            headers: &HeaderMap,
            cookie_jar: &mut cookie::CookieJar,
            body_bytes: &[u8],
        ) -> Result<Response<Body>> {
            match action_name {
                #(#action_matches)*
                _ => Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::from(format!("Action '{}' not found", action_name)))
                    .unwrap()),
            }
        }
    }
}

fn generate_enqueue_module(queue_tasks: &[QueueTaskInfo]) -> TokenStream {
    if queue_tasks.is_empty() {
        return quote! {};
    }

    let enqueue_fns: Vec<TokenStream> = queue_tasks
        .iter()
        .map(|qt| {
            let fn_name = format_ident!("{}", qt.name);
            let task_name_str = &qt.name;
            let module_path: Vec<_> = vec![format_ident!("queue_task"), format_ident!("{}", qt.name)];

            quote! {
                pub async fn #fn_name(input: crate::#(#module_path)::*::Input) -> forte_sdk::anyhow::Result<()> {
                    let payload = forte_sdk::serde_json::to_value(&input)?;
                    let body = forte_sdk::serde_json::to_vec(&forte_sdk::serde_json::json!({
                        "task_name": #task_name_str,
                        "payload": payload,
                    }))?;
                    let url = std::env::var("FN0_QUEUE_URL")
                        .map_err(|_| forte_sdk::anyhow::anyhow!("FN0_QUEUE_URL is not set"))?;
                    let request = forte_sdk::http::Request::post(&url)
                        .header("Content-Type", "application/json")
                        .body(body)?;
                    let response = forte_sdk::http::Client::new().send(request).await?;
                    if !response.status().is_success() {
                        return Err(forte_sdk::anyhow::anyhow!(
                            "enqueue failed with status {}",
                            response.status()
                        ));
                    }
                    Ok(())
                }
            }
        })
        .collect();

    quote! {
        pub mod enqueue {
            #(#enqueue_fns)*
        }
    }
}

fn generate_queue_task_execute_handler(queue_tasks: &[QueueTaskInfo]) -> TokenStream {
    if queue_tasks.is_empty() {
        return quote! {
            async fn handle_queue_task_execute(
                _body_bytes: &[u8],
            ) -> Result<Response<Body>> {
                Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::from("No queue tasks defined"))
                    .unwrap())
            }
        };
    }

    let task_matches: Vec<TokenStream> = queue_tasks
        .iter()
        .map(|qt| {
            let name = &qt.name;
            let module_path: Vec<_> =
                vec![format_ident!("queue_task"), format_ident!("{}", qt.name)];

            quote! {
                #name => {
                    let input: crate::#(#module_path)::*::Input =
                        match forte_sdk::serde_json::from_value(payload.clone()) {
                            Ok(v) => v,
                            Err(e) => {
                                return Ok(Response::builder()
                                    .status(StatusCode::BAD_REQUEST)
                                    .body(Body::from(format!("invalid payload for task '{}': {}", task_name, e)))
                                    .unwrap());
                            }
                        };
                    crate::#(#module_path)::*::handle(input).await
                }
            }
        })
        .collect();

    quote! {
        async fn handle_queue_task_execute(
            body_bytes: &[u8],
        ) -> Result<Response<Body>> {
            let request: forte_sdk::serde_json::Value = match forte_sdk::serde_json::from_slice(body_bytes) {
                Ok(v) => v,
                Err(e) => {
                    return Ok(Response::builder()
                        .status(StatusCode::BAD_REQUEST)
                        .body(Body::from(format!("invalid request body: {}", e)))
                        .unwrap());
                }
            };
            let task_name = match request["task_name"].as_str() {
                Some(s) => s,
                None => {
                    return Ok(Response::builder()
                        .status(StatusCode::BAD_REQUEST)
                        .body(Body::from("missing or non-string task_name"))
                        .unwrap());
                }
            };
            let payload = &request["payload"];

            let result = match task_name {
                #(#task_matches)*
                _ => {
                    return Ok(Response::builder()
                        .status(StatusCode::NOT_FOUND)
                        .body(Body::from(format!("Queue task '{}' not found", task_name)))
                        .unwrap());
                }
            };

            match result {
                Ok(()) => Ok(Response::builder()
                    .status(StatusCode::OK)
                    .body(Body::empty())
                    .unwrap()),
                Err(e) => Ok(Response::builder()
                    .status(StatusCode::INTERNAL_SERVER_ERROR)
                    .body(Body::from(format!("{:?}", e)))
                    .unwrap()),
            }
        }
    }
}

fn generate_admin_task_handler(admin_tasks: &[AdminTaskInfo]) -> TokenStream {
    if admin_tasks.is_empty() {
        return quote! {
            async fn handle_admin_task(
                _task_name: &str,
                _headers: &HeaderMap,
                _body_bytes: &[u8],
            ) -> Result<Response<Body>> {
                Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::from("No admin tasks defined"))
                    .unwrap())
            }
        };
    }

    let task_matches: Vec<TokenStream> = admin_tasks
        .iter()
        .map(|at| {
            let name = &at.name;
            let module_path: Vec<_> = vec![format_ident!("admin"), format_ident!("{}", at.name)];

            quote! {
                #name => {
                    let input: crate::#(#module_path)::*::Input =
                        forte_sdk::serde_json::from_slice(body_bytes)?;
                    let output = crate::#(#module_path)::*::handle(input).await;
                    match output {
                        Ok(value) => {
                            let json = forte_sdk::serde_json::to_vec(&value)?;
                            Ok(Response::builder()
                                .status(StatusCode::OK)
                                .header("content-type", "application/json")
                                .body(Body::from(json))
                                .unwrap())
                        }
                        Err(e) => Ok(Response::builder()
                            .status(StatusCode::INTERNAL_SERVER_ERROR)
                            .body(Body::from(format!("{:?}", e)))
                            .unwrap()),
                    }
                }
            }
        })
        .collect();

    quote! {
        #[forte_sdk::tracing::instrument(
            name = "handle_admin_task",
            skip_all,
            fields(task = task_name),
        )]
        async fn handle_admin_task(
            task_name: &str,
            headers: &HeaderMap,
            body_bytes: &[u8],
        ) -> Result<Response<Body>> {
            let is_admin = headers
                .get("x-fn0-admin")
                .and_then(|v| v.to_str().ok())
                .map(|v| v == "true")
                .unwrap_or(false);
            if !is_admin {
                return Ok(Response::builder()
                    .status(StatusCode::UNAUTHORIZED)
                    .body(Body::from("Unauthorized"))
                    .unwrap());
            }

            match task_name {
                #(#task_matches)*
                _ => Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::from(format!("Admin task '{}' not found", task_name)))
                    .unwrap()),
            }
        }
    }
}

fn generate_classify_route(pages: &[PageInfo]) -> TokenStream {
    let arms: Vec<TokenStream> = pages
        .iter()
        .map(|p| {
            let route_path = &p.route_path;
            if has_dynamic_segments(&p.route_segments) {
                let len = p.route_segments.len();
                let static_checks: Vec<TokenStream> = p
                    .route_segments
                    .iter()
                    .enumerate()
                    .filter_map(|(i, seg)| match seg {
                        RouteSegment::Static(s) => Some(quote! { path_segments[#i] == #s }),
                        RouteSegment::Dynamic(_) => None,
                    })
                    .collect();
                if static_checks.is_empty() {
                    quote! {
                        if path_segments.len() == #len {
                            return #route_path.to_string();
                        }
                    }
                } else {
                    quote! {
                        if path_segments.len() == #len && #(#static_checks)&&* {
                            return #route_path.to_string();
                        }
                    }
                }
            } else {
                quote! {
                    if path == #route_path {
                        return #route_path.to_string();
                    }
                }
            }
        })
        .collect();

    let needs_path_segments = pages
        .iter()
        .any(|p| has_dynamic_segments(&p.route_segments));
    let path_segments_decl = if needs_path_segments {
        quote! {
            let path_segments: Vec<&str> = path.trim_start_matches('/').split('/').collect();
        }
    } else {
        quote! {}
    };

    quote! {
        fn classify_route(path: &str) -> String {
            if path.strip_prefix("/__forte_action/").is_some() {
                return "/__forte_action/[name]".to_string();
            }
            if path.strip_prefix("/__forte_admin/").is_some() {
                return "/__forte_admin/[name]".to_string();
            }
            if path == "/__fn0_queue_task/execute" {
                return "/__fn0_queue_task/execute".to_string();
            }
            if path.strip_prefix("/__self_invoke/").is_some() {
                return "/__self_invoke/[name]".to_string();
            }
            #path_segments_decl
            #(#arms)*
            "unknown".to_string()
        }
    }
}

pub(super) fn generate_admin_mod(admin_tasks: &[AdminTaskInfo]) -> String {
    let mut content = String::new();
    content.push_str("// Auto-generated by forte build\n\n");
    for at in admin_tasks {
        content.push_str(&format!("pub mod {};\n", at.name));
    }
    content
}

pub(super) fn generate_actions_mod(actions: &[ActionInfo]) -> String {
    let mut content = String::new();
    content.push_str("// Auto-generated by forte build\n\n");
    let mut names: Vec<&str> = actions.iter().map(|a| a.name.as_str()).collect();
    names.sort();
    for name in names {
        content.push_str(&format!("pub mod {};\n", name));
    }
    content
}

pub(super) fn generate_queue_task_mod(queue_tasks: &[QueueTaskInfo]) -> String {
    let mut content = String::new();
    content.push_str("// Auto-generated by forte build\n\n");
    for qt in queue_tasks {
        content.push_str(&format!("pub mod {};\n", qt.name));
    }
    content
}

pub(super) fn generate_fe_paths(pages: &[PageInfo]) -> String {
    let mut content = String::new();
    content.push_str("// Auto-generated by forte build\n\n");
    content.push_str("export const paths = {\n");

    for page in pages {
        // Convert [id] to :id format for the key
        let route_path = page
            .route_segments
            .iter()
            .map(|seg| match seg {
                RouteSegment::Static(s) => s.clone(),
                RouteSegment::Dynamic(name) => format!(":{}", name),
            })
            .collect::<Vec<_>>();
        let route_path = if route_path.is_empty() {
            "/".to_string()
        } else {
            format!("/{}", route_path.join("/"))
        };

        if let Some(path_params) = &page.path_params {
            // Has dynamic params: "/post/:id": ({id}: {id: string}) => `/post/${id}`
            let param_names: Vec<&str> = path_params.iter().map(|p| p.name.as_str()).collect();
            let param_types: Vec<String> = path_params
                .iter()
                .map(|p| format!("{}: {}", p.name, rust_type_to_ts(&p.inner_type)))
                .collect();

            let path_template = page
                .route_segments
                .iter()
                .map(|seg| match seg {
                    RouteSegment::Static(s) => s.clone(),
                    RouteSegment::Dynamic(name) => format!("${{{}}}", name),
                })
                .collect::<Vec<_>>()
                .join("/");

            content.push_str(&format!(
                "  \"{}\": ({{{}}}: {{{}}}) => `/{}`",
                route_path,
                param_names.join(", "),
                param_types.join("; "),
                path_template
            ));
        } else {
            // No params: "/": () => "/"
            content.push_str(&format!("  \"{}\": () => \"{}\"", route_path, route_path));
        }

        content.push_str(",\n");
    }

    content.push_str("} as const;\n");
    content
}

fn rust_type_to_ts(rust_type: &str) -> &str {
    match rust_type {
        "String" | "&str" => "string",
        "i8" | "i16" | "i32" | "i64" | "u8" | "u16" | "u32" | "u64" | "f32" | "f64" | "isize"
        | "usize" => "number",
        "bool" => "boolean",
        _ => "string",
    }
}
