[package]
name = "fn0-control"
version = "0.1.2"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
aes-gcm = "0.10"
anyhow = "1"
base64 = "0.22"
cookie = "0.18"
hmac = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
http = "1"
forte-json = { path = "../../../forte/json" }
forte-sdk = { path = "../../../forte/sdk" }
doc-db = { package = "fn0-doc-db", path = "../../../doc-db" }
fn0-shared-schema = { path = "../../shared-schema", version = "=0.1.1" }
tracing = "=0.1.44"

[build-dependencies]
forte-codegen = { path = "../../../forte/codegen" }
