// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AwsLambdaCwasmCompiler extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'fn0:index:AwsLambdaCwasmCompiler';

    /**
     * Returns true if the given object is an instance of AwsLambdaCwasmCompiler.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AwsLambdaCwasmCompiler {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AwsLambdaCwasmCompiler.__pulumiType;
    }


    /**
     * Create a AwsLambdaCwasmCompiler resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AwsLambdaCwasmCompilerArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.cWasmBucket === undefined && !opts.urn) {
                throw new Error("Missing required property 'cWasmBucket'");
            }
            if (args?.queueArn === undefined && !opts.urn) {
                throw new Error("Missing required property 'queueArn'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            if (args?.wasmBucket === undefined && !opts.urn) {
                throw new Error("Missing required property 'wasmBucket'");
            }
            resourceInputs["cWasmBucket"] = args?.cWasmBucket;
            resourceInputs["queueArn"] = args?.queueArn;
            resourceInputs["region"] = args?.region;
            resourceInputs["wasmBucket"] = args?.wasmBucket;
        } else {
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AwsLambdaCwasmCompiler.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a AwsLambdaCwasmCompiler resource.
 */
export interface AwsLambdaCwasmCompilerArgs {
    cWasmBucket: pulumi.Input<string>;
    queueArn: pulumi.Input<string>;
    region: pulumi.Input<string>;
    wasmBucket: pulumi.Input<string>;
}
