// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class CwasmS3Pusher extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'fn0:index:CwasmS3Pusher';

    /**
     * Returns true if the given object is an instance of CwasmS3Pusher.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CwasmS3Pusher {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CwasmS3Pusher.__pulumiType;
    }

    declare public /*out*/ readonly cwasmZstBucket: pulumi.Output<string>;

    /**
     * Create a CwasmS3Pusher resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CwasmS3PusherArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.awsS3Region === undefined && !opts.urn) {
                throw new Error("Missing required property 'awsS3Region'");
            }
            if (args?.cloudflareApiToken === undefined && !opts.urn) {
                throw new Error("Missing required property 'cloudflareApiToken'");
            }
            if (args?.targetBuckets === undefined && !opts.urn) {
                throw new Error("Missing required property 'targetBuckets'");
            }
            if (args?.zoneId === undefined && !opts.urn) {
                throw new Error("Missing required property 'zoneId'");
            }
            resourceInputs["awsS3Region"] = args?.awsS3Region;
            resourceInputs["cloudflareApiToken"] = args?.cloudflareApiToken;
            resourceInputs["targetBuckets"] = args?.targetBuckets;
            resourceInputs["zoneId"] = args?.zoneId;
            resourceInputs["cwasmZstBucket"] = undefined /*out*/;
        } else {
            resourceInputs["cwasmZstBucket"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CwasmS3Pusher.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a CwasmS3Pusher resource.
 */
export interface CwasmS3PusherArgs {
    awsS3Region: pulumi.Input<string>;
    cloudflareApiToken: pulumi.Input<string>;
    targetBuckets: inputs.S3CompatibleBucketArgs[];
    zoneId: pulumi.Input<string>;
}
