// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ForteR2 extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'fn0:index:ForteR2';

    /**
     * Returns true if the given object is an instance of ForteR2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ForteR2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ForteR2.__pulumiType;
    }

    declare public /*out*/ readonly accessKeyId: pulumi.Output<string>;
    declare public readonly accountId: pulumi.Output<string>;
    declare public readonly bucketName: pulumi.Output<string>;
    declare public /*out*/ readonly endpoint: pulumi.Output<string>;
    declare public /*out*/ readonly publicBaseUrl: pulumi.Output<string>;
    declare public /*out*/ readonly secretAccessKey: pulumi.Output<string>;

    /**
     * Create a ForteR2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ForteR2Args, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.accountId === undefined && !opts.urn) {
                throw new Error("Missing required property 'accountId'");
            }
            if (args?.bucketName === undefined && !opts.urn) {
                throw new Error("Missing required property 'bucketName'");
            }
            if (args?.domain === undefined && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            if (args?.staticHostname === undefined && !opts.urn) {
                throw new Error("Missing required property 'staticHostname'");
            }
            if (args?.zoneId === undefined && !opts.urn) {
                throw new Error("Missing required property 'zoneId'");
            }
            resourceInputs["accountId"] = args?.accountId;
            resourceInputs["bucketName"] = args?.bucketName;
            resourceInputs["domain"] = args?.domain;
            resourceInputs["location"] = args?.location;
            resourceInputs["staticHostname"] = args?.staticHostname;
            resourceInputs["zoneId"] = args?.zoneId;
            resourceInputs["accessKeyId"] = undefined /*out*/;
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["publicBaseUrl"] = undefined /*out*/;
            resourceInputs["secretAccessKey"] = undefined /*out*/;
        } else {
            resourceInputs["accessKeyId"] = undefined /*out*/;
            resourceInputs["accountId"] = undefined /*out*/;
            resourceInputs["bucketName"] = undefined /*out*/;
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["publicBaseUrl"] = undefined /*out*/;
            resourceInputs["secretAccessKey"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ForteR2.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a ForteR2 resource.
 */
export interface ForteR2Args {
    accountId: pulumi.Input<string>;
    bucketName: pulumi.Input<string>;
    domain: pulumi.Input<string>;
    location?: pulumi.Input<string | undefined>;
    staticHostname: pulumi.Input<string>;
    zoneId: pulumi.Input<string>;
}
