// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ForteDb owns the Turso group ("forte-db") that holds one database per
 * deployed forte app. Databases are created on demand by HQ at `forte deploy`
 * time. A single group-scoped auth token is issued here and handed to workers
 * so they can speak hrana to any app database without per-db credentials.
 */
export class ForteDb extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'fn0:index:ForteDb';

    /**
     * Returns true if the given object is an instance of ForteDb.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ForteDb {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ForteDb.__pulumiType;
    }

    declare public /*out*/ readonly groupName: pulumi.Output<string>;
    declare public /*out*/ readonly groupToken: pulumi.Output<string>;
    declare public /*out*/ readonly hostSuffix: pulumi.Output<string>;

    /**
     * Create a ForteDb resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ForteDbArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.location === undefined && !opts.urn) {
                throw new Error("Missing required property 'location'");
            }
            if (args?.organizationSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationSlug'");
            }
            resourceInputs["location"] = args?.location;
            resourceInputs["organizationSlug"] = args?.organizationSlug;
            resourceInputs["groupName"] = undefined /*out*/;
            resourceInputs["groupToken"] = undefined /*out*/;
            resourceInputs["hostSuffix"] = undefined /*out*/;
        } else {
            resourceInputs["groupName"] = undefined /*out*/;
            resourceInputs["groupToken"] = undefined /*out*/;
            resourceInputs["hostSuffix"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ForteDb.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a ForteDb resource.
 */
export interface ForteDbArgs {
    location: pulumi.Input<string>;
    organizationSlug: pulumi.Input<string>;
}
