// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { B2CloudflareStaticCdnArgs } from "./b2cloudflareStaticCdn";
export type B2CloudflareStaticCdn = import("./b2cloudflareStaticCdn").B2CloudflareStaticCdn;
export const B2CloudflareStaticCdn: typeof import("./b2cloudflareStaticCdn").B2CloudflareStaticCdn = null as any;
utilities.lazyLoad(exports, ["B2CloudflareStaticCdn"], () => require("./b2cloudflareStaticCdn"));

export { CloudflareDnsArgs } from "./cloudflareDns";
export type CloudflareDns = import("./cloudflareDns").CloudflareDns;
export const CloudflareDns: typeof import("./cloudflareDns").CloudflareDns = null as any;
utilities.lazyLoad(exports, ["CloudflareDns"], () => require("./cloudflareDns"));

export { ForteDbArgs } from "./forteDb";
export type ForteDb = import("./forteDb").ForteDb;
export const ForteDb: typeof import("./forteDb").ForteDb = null as any;
utilities.lazyLoad(exports, ["ForteDb"], () => require("./forteDb"));

export { ForteR2Args } from "./forteR2";
export type ForteR2 = import("./forteR2").ForteR2;
export const ForteR2: typeof import("./forteR2").ForteR2 = null as any;
utilities.lazyLoad(exports, ["ForteR2"], () => require("./forteR2"));

export { OciComputeWorkerArgs } from "./ociComputeWorker";
export type OciComputeWorker = import("./ociComputeWorker").OciComputeWorker;
export const OciComputeWorker: typeof import("./ociComputeWorker").OciComputeWorker = null as any;
utilities.lazyLoad(exports, ["OciComputeWorker"], () => require("./ociComputeWorker"));

export { OciGlobalVaultArgs } from "./ociGlobalVault";
export type OciGlobalVault = import("./ociGlobalVault").OciGlobalVault;
export const OciGlobalVault: typeof import("./ociGlobalVault").OciGlobalVault = null as any;
utilities.lazyLoad(exports, ["OciGlobalVault"], () => require("./ociGlobalVault"));

export { OciHeadQuarterArgs } from "./ociHeadQuarter";
export type OciHeadQuarter = import("./ociHeadQuarter").OciHeadQuarter;
export const OciHeadQuarter: typeof import("./ociHeadQuarter").OciHeadQuarter = null as any;
utilities.lazyLoad(exports, ["OciHeadQuarter"], () => require("./ociHeadQuarter"));

export { OciHeadQuarterVcnArgs } from "./ociHeadQuarterVcn";
export type OciHeadQuarterVcn = import("./ociHeadQuarterVcn").OciHeadQuarterVcn;
export const OciHeadQuarterVcn: typeof import("./ociHeadQuarterVcn").OciHeadQuarterVcn = null as any;
utilities.lazyLoad(exports, ["OciHeadQuarterVcn"], () => require("./ociHeadQuarterVcn"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { SuffixArgs } from "./suffix";
export type Suffix = import("./suffix").Suffix;
export const Suffix: typeof import("./suffix").Suffix = null as any;
utilities.lazyLoad(exports, ["Suffix"], () => require("./suffix"));

export { TursoDocDbArgs } from "./tursoDocDb";
export type TursoDocDb = import("./tursoDocDb").TursoDocDb;
export const TursoDocDb: typeof import("./tursoDocDb").TursoDocDb = null as any;
utilities.lazyLoad(exports, ["TursoDocDb"], () => require("./tursoDocDb"));


// Export sub-modules:
import * as types from "./types";

export {
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "fn0:index:B2CloudflareStaticCdn":
                return new B2CloudflareStaticCdn(name, <any>undefined, { urn })
            case "fn0:index:CloudflareDns":
                return new CloudflareDns(name, <any>undefined, { urn })
            case "fn0:index:ForteDb":
                return new ForteDb(name, <any>undefined, { urn })
            case "fn0:index:ForteR2":
                return new ForteR2(name, <any>undefined, { urn })
            case "fn0:index:OciComputeWorker":
                return new OciComputeWorker(name, <any>undefined, { urn })
            case "fn0:index:OciGlobalVault":
                return new OciGlobalVault(name, <any>undefined, { urn })
            case "fn0:index:OciHeadQuarter":
                return new OciHeadQuarter(name, <any>undefined, { urn })
            case "fn0:index:OciHeadQuarterVcn":
                return new OciHeadQuarterVcn(name, <any>undefined, { urn })
            case "fn0:index:Suffix":
                return new Suffix(name, <any>undefined, { urn })
            case "fn0:index:TursoDocDb":
                return new TursoDocDb(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("fn0", "index", _module)
pulumi.runtime.registerResourcePackage("fn0", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:fn0") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
