// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class OciHeadQuarterVcn extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'fn0:index:OciHeadQuarterVcn';

    /**
     * Returns true if the given object is an instance of OciHeadQuarterVcn.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OciHeadQuarterVcn {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OciHeadQuarterVcn.__pulumiType;
    }

    declare public /*out*/ readonly compartmentId: pulumi.Output<string>;
    declare public /*out*/ readonly ipv6cidrBlocks: pulumi.Output<string[]>;
    declare public /*out*/ readonly vcnId: pulumi.Output<string>;

    /**
     * Create a OciHeadQuarterVcn resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OciHeadQuarterVcnArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            if (args?.suffix === undefined && !opts.urn) {
                throw new Error("Missing required property 'suffix'");
            }
            resourceInputs["region"] = args?.region;
            resourceInputs["suffix"] = args?.suffix;
            resourceInputs["compartmentId"] = undefined /*out*/;
            resourceInputs["ipv6cidrBlocks"] = undefined /*out*/;
            resourceInputs["vcnId"] = undefined /*out*/;
        } else {
            resourceInputs["compartmentId"] = undefined /*out*/;
            resourceInputs["ipv6cidrBlocks"] = undefined /*out*/;
            resourceInputs["vcnId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OciHeadQuarterVcn.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a OciHeadQuarterVcn resource.
 */
export interface OciHeadQuarterVcnArgs {
    region: pulumi.Input<string>;
    suffix: pulumi.Input<string>;
}
