// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class OciHeadQuarter extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'fn0:index:OciHeadQuarter';

    /**
     * Returns true if the given object is an instance of OciHeadQuarter.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OciHeadQuarter {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OciHeadQuarter.__pulumiType;
    }

    declare public /*out*/ readonly kubeconfig: pulumi.Output<string>;

    /**
     * Create a OciHeadQuarter resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OciHeadQuarterArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.certificate === undefined && !opts.urn) {
                throw new Error("Missing required property 'certificate'");
            }
            if (args?.compartmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'compartmentId'");
            }
            if (args?.dnsProvider === undefined && !opts.urn) {
                throw new Error("Missing required property 'dnsProvider'");
            }
            if (args?.docDbToken === undefined && !opts.urn) {
                throw new Error("Missing required property 'docDbToken'");
            }
            if (args?.docDbUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'docDbUrl'");
            }
            if (args?.grafanaRegion === undefined && !opts.urn) {
                throw new Error("Missing required property 'grafanaRegion'");
            }
            if (args?.grafanaSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'grafanaSlug'");
            }
            if (args?.ipv6cidrBlocks === undefined && !opts.urn) {
                throw new Error("Missing required property 'ipv6cidrBlocks'");
            }
            if (args?.ociRegion === undefined && !opts.urn) {
                throw new Error("Missing required property 'ociRegion'");
            }
            if (args?.selfDnsCloudflareApiToken === undefined && !opts.urn) {
                throw new Error("Missing required property 'selfDnsCloudflareApiToken'");
            }
            if (args?.selfDnsCloudflareZoneId === undefined && !opts.urn) {
                throw new Error("Missing required property 'selfDnsCloudflareZoneId'");
            }
            if (args?.selfDnsHostname === undefined && !opts.urn) {
                throw new Error("Missing required property 'selfDnsHostname'");
            }
            if (args?.sites === undefined && !opts.urn) {
                throw new Error("Missing required property 'sites'");
            }
            if (args?.suffix === undefined && !opts.urn) {
                throw new Error("Missing required property 'suffix'");
            }
            if (args?.vcnId === undefined && !opts.urn) {
                throw new Error("Missing required property 'vcnId'");
            }
            resourceInputs["certificate"] = args?.certificate;
            resourceInputs["compartmentId"] = args?.compartmentId;
            resourceInputs["dnsProvider"] = args?.dnsProvider;
            resourceInputs["docDbToken"] = args?.docDbToken;
            resourceInputs["docDbUrl"] = args?.docDbUrl;
            resourceInputs["grafanaRegion"] = args?.grafanaRegion;
            resourceInputs["grafanaSlug"] = args?.grafanaSlug;
            resourceInputs["ipv6cidrBlocks"] = args?.ipv6cidrBlocks;
            resourceInputs["ociRegion"] = args?.ociRegion;
            resourceInputs["selfDnsCloudflareApiToken"] = args?.selfDnsCloudflareApiToken;
            resourceInputs["selfDnsCloudflareZoneId"] = args?.selfDnsCloudflareZoneId;
            resourceInputs["selfDnsHostname"] = args?.selfDnsHostname;
            resourceInputs["sites"] = args?.sites;
            resourceInputs["suffix"] = args?.suffix;
            resourceInputs["vcnId"] = args?.vcnId;
            resourceInputs["kubeconfig"] = undefined /*out*/;
        } else {
            resourceInputs["kubeconfig"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OciHeadQuarter.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a OciHeadQuarter resource.
 */
export interface OciHeadQuarterArgs {
    certificate: pulumi.Input<string>;
    compartmentId: pulumi.Input<string>;
    dnsProvider: pulumi.Input<inputs.DnsProviderArgArgs>;
    docDbToken: pulumi.Input<string>;
    docDbUrl: pulumi.Input<string>;
    grafanaRegion: pulumi.Input<string>;
    grafanaSlug: pulumi.Input<string>;
    ipv6cidrBlocks: pulumi.Input<string[]>;
    ociRegion: pulumi.Input<string>;
    selfDnsCloudflareApiToken: pulumi.Input<string>;
    selfDnsCloudflareZoneId: pulumi.Input<string>;
    selfDnsHostname: pulumi.Input<string>;
    sites: pulumi.Input<inputs.SiteArgsArgs[]>;
    suffix: pulumi.Input<string>;
    vcnId: pulumi.Input<string>;
}
