// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TursoDocDb extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'fn0:index:TursoDocDb';

    /**
     * Returns true if the given object is an instance of TursoDocDb.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TursoDocDb {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TursoDocDb.__pulumiType;
    }

    declare public /*out*/ readonly token: pulumi.Output<string>;
    declare public /*out*/ readonly url: pulumi.Output<string>;

    /**
     * Create a TursoDocDb resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TursoDocDbArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.location === undefined && !opts.urn) {
                throw new Error("Missing required property 'location'");
            }
            if (args?.organizationSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationSlug'");
            }
            resourceInputs["location"] = args?.location;
            resourceInputs["organizationSlug"] = args?.organizationSlug;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        } else {
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TursoDocDb.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a TursoDocDb resource.
 */
export interface TursoDocDbArgs {
    location: pulumi.Input<string>;
    organizationSlug: pulumi.Input<string>;
}
