// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

import * as pulumiAws from "@pulumi/aws";

export class AwsWatchdogVpc extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'fn0:index:AwsWatchdogVpc';

    /**
     * Returns true if the given object is an instance of AwsWatchdogVpc.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AwsWatchdogVpc {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AwsWatchdogVpc.__pulumiType;
    }

    declare public /*out*/ readonly ipv6CiderBlock: pulumi.Output<string>;
    declare public /*out*/ readonly securityGroup: pulumi.Output<pulumiAws.ec2.SecurityGroup>;
    declare public /*out*/ readonly subnet: pulumi.Output<pulumiAws.ec2.Subnet>;
    declare public /*out*/ readonly vpc: pulumi.Output<pulumiAws.ec2.Vpc>;

    /**
     * Create a AwsWatchdogVpc resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AwsWatchdogVpcArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["region"] = args?.region;
            resourceInputs["ipv6CiderBlock"] = undefined /*out*/;
            resourceInputs["securityGroup"] = undefined /*out*/;
            resourceInputs["subnet"] = undefined /*out*/;
            resourceInputs["vpc"] = undefined /*out*/;
        } else {
            resourceInputs["ipv6CiderBlock"] = undefined /*out*/;
            resourceInputs["securityGroup"] = undefined /*out*/;
            resourceInputs["subnet"] = undefined /*out*/;
            resourceInputs["vpc"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AwsWatchdogVpc.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a AwsWatchdogVpc resource.
 */
export interface AwsWatchdogVpcArgs {
    region: pulumi.Input<string>;
}
