// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class AwsWatchdog extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'fn0:index:AwsWatchdog';

    /**
     * Returns true if the given object is an instance of AwsWatchdog.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AwsWatchdog {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AwsWatchdog.__pulumiType;
    }


    /**
     * Create a AwsWatchdog resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AwsWatchdogArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.cloudflareEnvs === undefined && !opts.urn) {
                throw new Error("Missing required property 'cloudflareEnvs'");
            }
            if (args?.domain === undefined && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            if (args?.maxGracefulShutdownWaitSecs === undefined && !opts.urn) {
                throw new Error("Missing required property 'maxGracefulShutdownWaitSecs'");
            }
            if (args?.maxHealthyCheckRetries === undefined && !opts.urn) {
                throw new Error("Missing required property 'maxHealthyCheckRetries'");
            }
            if (args?.maxStartTimeoutSecs === undefined && !opts.urn) {
                throw new Error("Missing required property 'maxStartTimeoutSecs'");
            }
            if (args?.maxStartingCount === undefined && !opts.urn) {
                throw new Error("Missing required property 'maxStartingCount'");
            }
            if (args?.ociWorkerInfraEnvs === undefined && !opts.urn) {
                throw new Error("Missing required property 'ociWorkerInfraEnvs'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            if (args?.securityGroupId === undefined && !opts.urn) {
                throw new Error("Missing required property 'securityGroupId'");
            }
            if (args?.subnetId === undefined && !opts.urn) {
                throw new Error("Missing required property 'subnetId'");
            }
            if (args?.vpcId === undefined && !opts.urn) {
                throw new Error("Missing required property 'vpcId'");
            }
            resourceInputs["cloudflareEnvs"] = args?.cloudflareEnvs;
            resourceInputs["domain"] = args?.domain;
            resourceInputs["maxGracefulShutdownWaitSecs"] = args?.maxGracefulShutdownWaitSecs;
            resourceInputs["maxHealthyCheckRetries"] = args?.maxHealthyCheckRetries;
            resourceInputs["maxStartTimeoutSecs"] = args?.maxStartTimeoutSecs;
            resourceInputs["maxStartingCount"] = args?.maxStartingCount;
            resourceInputs["ociWorkerInfraEnvs"] = args?.ociWorkerInfraEnvs;
            resourceInputs["region"] = args?.region;
            resourceInputs["securityGroupId"] = args?.securityGroupId;
            resourceInputs["subnetId"] = args?.subnetId;
            resourceInputs["vpcId"] = args?.vpcId;
        } else {
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AwsWatchdog.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a AwsWatchdog resource.
 */
export interface AwsWatchdogArgs {
    cloudflareEnvs: pulumi.Input<inputs.CloudflareEnvsArgs>;
    domain: pulumi.Input<string>;
    maxGracefulShutdownWaitSecs: pulumi.Input<number>;
    maxHealthyCheckRetries: pulumi.Input<number>;
    maxStartTimeoutSecs: pulumi.Input<number>;
    maxStartingCount: pulumi.Input<number>;
    ociWorkerInfraEnvs: pulumi.Input<inputs.OciWorkerInfraEnvsArgs>;
    region: pulumi.Input<string>;
    securityGroupId: pulumi.Input<string>;
    subnetId: pulumi.Input<string>;
    vpcId: pulumi.Input<string>;
}
