// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AwsWatchdogArgs } from "./awsWatchdog";
export type AwsWatchdog = import("./awsWatchdog").AwsWatchdog;
export const AwsWatchdog: typeof import("./awsWatchdog").AwsWatchdog = null as any;
utilities.lazyLoad(exports, ["AwsWatchdog"], () => require("./awsWatchdog"));

export { AwsWatchdogVpcArgs } from "./awsWatchdogVpc";
export type AwsWatchdogVpc = import("./awsWatchdogVpc").AwsWatchdogVpc;
export const AwsWatchdogVpc: typeof import("./awsWatchdogVpc").AwsWatchdogVpc = null as any;
utilities.lazyLoad(exports, ["AwsWatchdogVpc"], () => require("./awsWatchdogVpc"));

export { OciComputeWorkerArgs } from "./ociComputeWorker";
export type OciComputeWorker = import("./ociComputeWorker").OciComputeWorker;
export const OciComputeWorker: typeof import("./ociComputeWorker").OciComputeWorker = null as any;
utilities.lazyLoad(exports, ["OciComputeWorker"], () => require("./ociComputeWorker"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));


// Export sub-modules:
import * as types from "./types";

export {
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "fn0:index:AwsWatchdog":
                return new AwsWatchdog(name, <any>undefined, { urn })
            case "fn0:index:AwsWatchdogVpc":
                return new AwsWatchdogVpc(name, <any>undefined, { urn })
            case "fn0:index:OciComputeWorker":
                return new OciComputeWorker(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("fn0", "index", _module)
pulumi.runtime.registerResourcePackage("fn0", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:fn0") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
