// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class OciComputeWorker extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'fn0:index:OciComputeWorker';

    /**
     * Returns true if the given object is an instance of OciComputeWorker.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OciComputeWorker {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OciComputeWorker.__pulumiType;
    }

    declare public /*out*/ readonly compartmentId: pulumi.Output<string>;
    declare public /*out*/ readonly infraEnvs: pulumi.Output<outputs.OciWorkerInfraEnvs>;
    declare public /*out*/ readonly instanceConfigurationId: pulumi.Output<string>;

    /**
     * Create a OciComputeWorker resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OciComputeWorkerArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            if (args?.watchdogIpv6CiderBlock === undefined && !opts.urn) {
                throw new Error("Missing required property 'watchdogIpv6CiderBlock'");
            }
            resourceInputs["region"] = args?.region;
            resourceInputs["watchdogIpv6CiderBlock"] = args?.watchdogIpv6CiderBlock;
            resourceInputs["compartmentId"] = undefined /*out*/;
            resourceInputs["infraEnvs"] = undefined /*out*/;
            resourceInputs["instanceConfigurationId"] = undefined /*out*/;
        } else {
            resourceInputs["compartmentId"] = undefined /*out*/;
            resourceInputs["infraEnvs"] = undefined /*out*/;
            resourceInputs["instanceConfigurationId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OciComputeWorker.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a OciComputeWorker resource.
 */
export interface OciComputeWorkerArgs {
    region: pulumi.Input<string>;
    watchdogIpv6CiderBlock: pulumi.Input<string>;
}
