// Auto-generated by forte build

export const paths = {
  "/": () => "/",
  "/api/runtime": () => "/api/runtime",
  "/api/dodb": () => "/api/dodb",
  "/api/storage": () => "/api/storage",
} as const;
