[package]
name = "fn0-wasmtime"
version = "0.1.3"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Wasmtime wrapper for fn0"

[dependencies]
sysinfo = { workspace = true }
wasmtime = { workspace = true, features = [
    "runtime",
    "cranelift",
    "component-model",
    "component-model-async",
    "memory-protection-keys",
    "parallel-compilation",
    "cache",
] }
zstd = { workspace = true }
