name: fn0Cloud
description: fn0Cloud
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  fn0Cloud:cloudflareAccountId:
    type: string
  fn0Cloud:cloudflareZoneId:
    type: string
  fn0Cloud:domain:
    type: string
  fn0Cloud:ociComputeWorkerRegion:
    type: string
  fn0Cloud:ociVaultRegion:
    type: string
  fn0Cloud:signyHostname:
    type: string
  fn0Cloud:collectyImageRef:
    type: string
  fn0Cloud:signyImageRef:
    type: string
  fn0Cloud:telemetryConfigVersion:
    type: string
  fn0Cloud:dodbRuntimeAddr:
    type: string
  fn0Cloud:dodbRuntimeServerName:
    type: string
  fn0Cloud:dodbRuntimeRootCertPemBase64:
    type: string
packages:
  fn0: ../pulumi@0.0.0
